name: env_gempy21

channels:
  - conda-forge
  - defaults
dependencies: 
  - python=3.8
  - pandas=1.3.4
  - numpy=1.19.0
  - scipy
  - mkl-service
  - libpython
  - m2w64-toolchain
  - pytest
  - git
  - Theano
  - pygpu
  - geopandas
  - rasterio
  - matplotlib
  - networkx
  - scikit-image>=0.17.2
  - pyvista=0.24
  - iPython
  - jupyter
  - notebook
  - pymc3=3.8
  - arviz=0.10.0
  - pyevtk
  - requests
  - pip
  - pip:
    - qgrid==1.3.0
    - mplstereonet
    - pyqt5
    - gempy==2.1.0
