name: env_gempyMac
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - jupyter
  - matplotlib
  - python
  - pandas
  - numpy
  - scipy
  - mkl-service
  - libpython
  - m2w64-toolchain
  - pytest
  - sphinx
  - Theano
  - pygpu
  - geopandas
  - rasterio
  - matplotlib
  - seaborn>=0.9
  - scikit-image>=0.17.2
  - pyvista=0.24
  - pip
  - pip:
      - subsurface
      - git+https://github.com/cgre-aachen/gempy.git

