name: env_datasci

channels:
  - conda-forge
  - defaults
dependencies: 
  - python=3.10
  - pandas
  - matplotlib
  - altair
  - bokeh
  - numpy
  - scipy
  - seaborn
  - scikit-image
  - scikit-learn
  - imbalanced-learn
  - iPython
  - jupyter
  - notebook
  - vega_datasets
  - pydot
  - pip
