name: gempygis_env_py38

channels:
  - conda-forge
  - defaults
dependencies: 
  - python=3.8
  - numpy
  - scooby
  - pandas
  - geopandas
  - pygeos
  - rasterio
  - matplotlib
  - shapely
  - scikit-image>=0.17.2
  - scikit-learn
  - xmltodict
  - scipy
  - mkl-service
  - pyvista
  - pyvistaqt
  - pytest
  - owslib
  - descartes
  - iPython
  - mkl-service
  - libpython
  - m2w64-toolchain
  - Theano>=1.0.4 # In windows use conda! This will install all the required compilers
  - pytest
  - seaborn>=0.9
  - bokeh
  - bqplot
  - ipywidgets
  - networkx
  - pymc3
  - pyevtk
  - requests
  - gemgis
  - pip
  - pip:
    - qgrid==1.3.0
    - mplstereonet
    - pyqrcode
    - pyqt5
    - gempy
