name: env_gempy_Mac
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - ipython
  - jupyter
  - matplotlib
  - pandas
  - numpy<=1.12
  - scipy<0.17.1
  - mkl-service
  - pytest
  - sphinx
  - theano
  - pygpu
  - geopandas
  - rasterio
  - seaborn>=0.9
  - scikit-image>=0.17.2
  - pyvista
  - pip
  - pip:
      - subsurface
      - pyqt5
      - gempy