name: gemgis_env

channels:
  - conda-forge
  - defaults
dependencies: 
  - python=3.7
  - numpy
  - scooby
  - pandas
  - geopandas=0.7
  - rasterio
  - matplotlib
  - shapely
  - scikit-image>=0.17.2
  - xmltodict
  - scipy
  - mkl-service
  - pyvista=0.24
  - pytest
  - owslib
  - descartes
  - iPython
  - pip
  - pip:
    - qgrid==1.3.0
    - mplstereonet
    - pyqt5
