name: gempygis_env

channels:
  - conda-forge
  - defaults
dependencies: 
  - python=3.7
  - numpy
  - scooby
  - pandas
  - geopandas=0.7
  - rasterio
  - matplotlib
  - shapely
  - scikit-image>=0.17.2
  - scikit-learn
  - xmltodict
  - scipy
  - mkl-service
  - pyvista=0.24
  - pytest
  - owslib
  - descartes
  - iPython
  - Theano>=1.0.4 # In windows use conda! This will install all the required compilers
  - pytest
  - seaborn>=0.9
  - bqplot
  - ipywidgets
  - networkx
  - pymc3
  - pyevtk
  - requests
  - pip
  - pip:
    - qgrid==1.3.0
    - mplstereonet
    - pyqrcode
    - pyqt5
    - gempy
