name: geo_aesara_py39

channels:
  - conda-forge
  - defaults
dependencies: 
  - python=3.9
  - numpy
  - scooby
  - pandas=1.3.5
  - geopandas
  - cartopy
  - geoplot
  - pygeos
  - rasterio
  - matplotlib
  - shapely
  - scikit-image>=0.17.2
  - scikit-learn
  - xmltodict
  - scipy
  - pyvista
  - pyvistaqt
  - pytest
  - owslib
  - iPython
  - pytest
  - seaborn>=0.9
  - bokeh
  - bqplot
  - ipywidgets
  - aesara
  - pymc>=4
  - pip
  - pip:
    - qgrid==1.3.0
    - mplstereonet
    - pyqrcode
    - pyqt5
    - welly
    - wellpathpy
    - striplog
    - subsurface
    - pvgeo
