name: env_geo_linux

channels:
  - conda-forge
  - defaults
dependencies: 
  - python=3.8
  - pandas=1.3.4
  - geopandas
  - rasterio
  - cartopy
  - geoplot
  - shapely
  - matplotlib
  - Theano>=1.0.4 # In windows use conda! This will install all the required compilers
  - numpy
  - scipy
  - mkl-service
  - pytest
  - seaborn>=0.9
  - networkx
  - scikit-image>=0.17.2
  - pyvista
  - pyvistaqt
  - iPython
  - ipywidgets
  - pymc3
  - pyevtk
  - requests
  - gemgis
  - pip
  - pip:
    - qgrid==1.3.0
    - mplstereonet
    - pyqrcode
    - pyqt5
    - gempy
    - welly
    - wellpathpy
    - striplog
    - subsurface
