name: env_geo_Mac
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipython
  - ipywidgets
  - jupyter
  - matplotlib
  - pandas=1.3.4
  - numpy
  - scipy
  - mkl-service
  - pytest
  - sphinx
  - theano>=1.0.4
  - pygpu
  - geopandas
  - rasterio
  - cartopy
  - geoplot
  - shapely
  - seaborn>=0.9
  - scikit-image>=0.17.2
  - pyvista
  - pyvistaqt
  - pyevtk
  - gemgis
  - pip
  - pip:
      - subsurface
      - pyqt5
      - gempy
      - welly
      - wellpathpy
      - striplog
      - subsurface